---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-net-api-deployment
  labels:
    app: dummy-net-api
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: dummy-net-api
  template:
    metadata:
      labels:
        app: dummy-net-api
    spec:
      containers:
      - name: dummy-net-api
        image: huseyinutkuaslan/dummy-net-api
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-net-api-service
  labels:
    app: dummy-net-api
spec:
  selector:
    app: dummy-net-api
  ports:
  - protocol: TCP
    port: 5000 # Port is the port the service is listening on.
    targetPort: 80 # Where is being redirected the entry port, so this is the port the PODS are listening.
  type: LoadBalancer

