---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-net-api-deployment
  labels:
    app: dummy-net-api
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: dummy-net-api
  template:
    metadata:
      labels:
        app: dummy-net-api
    spec:
      containers:
      - name: dummy-net-api
        image: huseyinutkuaslan/dummy-net-api
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        ports:
          - containerPort: 5000