resources:
- name: app-repo
  type: git
  icon: github
  source:
    uri: "https://github.com/HuseyinUtkuASLAN/dummy-net-api.git"
    branch: "main"

- name: docker-demo
  type: docker-image
  source:
    repository: huseyinutkuaslan/dummy-net-api
    username: ((docker-hub-user-name))
    password: ((docker-hub-password))

jobs:

- name: build-test-and-publish-to-hub
  public: true

  plan:
  - get: app-repo
    trigger: true
  
  - task: test
    config:
      inputs:
      - name : app-repo
      platform : linux
      image_resource:
        type: registry-image
         # there is a bug for linux version.
         # for .net core 3.1, when 'dotnet test' is run, a known bug happens and can not proceed
        source: { repository: mcr.microsoft.com/dotnet/sdk }
      run:
        path: sh
        args: 
          - -exc
          - |
            cd app-repo/src/dummy-api
            dotnet restore
            dotnet build
            dotnet test
  
  - task: publish
    config:
      inputs: 
      - name: app-repo
      outputs:
      - name: published-files
      platform : linux
      image_resource:
        type: registry-image
        source: { repository: mcr.microsoft.com/dotnet/sdk }
      run:
        path: sh
        args: 
          - -exc
          - |
            dotnet publish -c Release app-repo/src/dummy-api
            cp app-repo/src/dummy-api/dummy-api/bin/Release/netcoreapp3.1/publish/* published-files/
            cp app-repo/ci/runtime-image/Dockerfile published-files/
  - put: docker-demo
    params:
      build: published-files
# # - name: auto-testing
# # - name: manuel-acceptance
# # - name: deploy